# Generated by Django 3.0.5 on 2020-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='content',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='açıklama'),
        ),
    ]
