# Generated by Django 3.0.5 on 2020-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_auto_20200425_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='statu',
            field=models.CharField(choices=[('P', 'pasif'), ('A', 'aktif')], default='A', max_length=1),
        ),
    ]
